language: node_js
node_js:
  - "8"
script:
- cd updater
- npm i
- bash release.sh
- cd ../plugin/
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: phpstorm-library-plugin.jar
  skip_cleanup: true
  on:
    tags: true
